import pyautogui   
import pyperclip
import time
from selenium import webdriver

# Passo 1 iniciar, encerrar e salvar na pasta a gravação da tela
pyautogui.click(x=856, y=188, clicks=1) #altere essa linha conforme o tamanho da sua tela (area do click "area de trabalho")
time.sleep(2)
pyautogui.write('Free Cam 8')
time.sleep(4)
pyautogui.press('enter')
time.sleep(7)
pyautogui.click(x=535, y=377) #altere conforme a sua tela (area de click "new recording")
time.sleep(4)
pyautogui.click(x=349, y=705) #altere conforme a suua tela (area de click "ajuste de resolução")
time.sleep(2)
pyautogui.click(x=333, y=619) #altere conforme a sua tela (area de click "fullscreen")
time.sleep(2)
pyautogui.click(x=333, y=625) #altere conforme a suua tela (area de click "nome do seu monitor")
time.sleep(2)
pyautogui.click(x=33, y=706) #altere conforme a ssua tela (area de click "start recording")
time.sleep(5)
# Entrar na aula
aula = webdriver.Firefox(executable_path=r'C:\Users\Caioz\Desktop\geckdriver/geckodriver')
aula.get('https://aluno.uninove.br/')
time.sleep(15)
pyautogui.click(x=467, y=380) #altere conforme a sua tela (area de click "username")
pyautogui.write('920105071')
pyautogui.press('tab')
pyautogui.write('Mcl415263@')
pyautogui.press('enter')
time.sleep(3)
pyautogui.click(x=1357, y=722, clicks=6) #altere conforme a sua tela (area de click "seta de rolagem")
time.sleep(1)
pyautogui.click(x=360, y=521) #altere conforme o tamanho da sua tela (area de click "acesso ao curso presencial" )
time.sleep(3)
pyautogui.click(x=1055, y=553) # alterer conforme o tamanho da sua tela (area de click dia respectivo da aula, altere conforme o dia da semana)
time.sleep(1)
pyautogui.click(x=419, y=583) # altere conforme a sua tela (area de click "microfone")
time.sleep(6)
pyautogui.click(x=430, y=576) #altere conforme a sua tela (area de click "webcam")
time.sleep(6)
pyautogui.click(x=1024, y=444) #altere conforme a sua tela (area de click "participar agora")
time.sleep(20) #tempo correto 7800
pyautogui.hotkey('esc')
time.sleep(5)
pyautogui.click(x=147, y=82)
time.sleep(3)
pyautogui.click(x=525, y=449)
# Passo 2 Abrir o google drive
driver = webdriver.Firefox(executable_path=r'C:\Users\Caioz\Desktop\geckdriver/geckodriver')
driver.get('https://drive.google.com/drive/folders/11jxXCM5DYNozIk7z0pq-zkUimKb3FeOZ')
time.sleep(5)
# Fazer login
pyautogui.click(x=1280, y=118) #altere essa linha conforme a sua tela (area de click "fazer login") só é necessario fazer essa alteração uma vez
time.sleep(3)
pyautogui.write('fcaio127@uni9.edu.br') #colocar suas credenciais aqui (email)
pyautogui.press('enter')
time.sleep(2)
pyautogui.write('mcl415263') #coloque suas credenciais aqui (senha)
pyautogui.press('enter')
time.sleep(5)
# Carregar o arquivo
pyautogui.click(x=70, y=189) #altere essa linha conforme a sua tela (area de click "Novo")
time.sleep(2)
pyautogui.click(x=105, y=238) #altere essa linha conforme a sua tela (area de click "upload de arquivos")
time.sleep(2)
pyautogui.click(x=155, y=388, clicks=6) #altere essa linha conforme a sua tela (area de click "seta de scroll")
time.sleep(2)
pyautogui.click(x=85, y=278, clicks=2) #altere essa linha conforme a sua tela (area de click "pasta com as capturas de telas")
time.sleep(2)
pyautogui.rightClick(x=567, y=295) #altere essa linha conforme a sua tela (area de click "ordenar por...")
time.sleep(2)
pyautogui.click(x=811, y=359) #altere essa linha conforme a sua tela (area de click "data")
time.sleep(1)
pyautogui.click(x=201, y=116)
time.sleep(2)
pyautogui.click(x=352, y=172) #altere essa linha conforme a sua tela (area de click "abrir")
time.sleep(20)
# Salve o arquivo 
pyautogui.press('f5')
# Desligue o computador
